Initial commit
Archangel37/CaesarCipher pull request #1
Opened 2018-04-26 09:19 UTC by Archangel37

2018-04-27 05:16 UTC, ilpoli requested changes

2018-04-27 05:16 UTC, ilpoli commented on СaesarCipher/EncoderDecoder.cs
> +                    Result += temp_alph[index].ToString();
нет смысла писать ToString(), char прекрасно прибавляется к строке.

2018-04-27 05:16 UTC, ilpoli commented on СaesarCipher/EncoderDecoder.cs
> +                                : temp_alph.Length + (temp_alph.IndexOf(ch) + shift) % temp_alph.Length;
не очень понимаю зачем это условие, почему не работает просто
```int index = (temp_alph.IndexOf(ch) + shift) % temp_alph.Length``` ?

2018-04-27 05:16 UTC, ilpoli commented on СaesarCipher/EncoderDecoder.cs
> +        };
можно просто было добавить все верхнем регистре а потом использовать ToLower чтоб добавить еще две записи.

2018-05-03 10:03 UTC, Archangel37 commented on СaesarCipher/EncoderDecoder.cs
> +                                : temp_alph.Length + (temp_alph.IndexOf(ch) + shift) % temp_alph.Length;
Просто потому, что если я обратное преобразование буду делать, то индекс выйдет отрицательным - а по такому условию, что ты привёл - я не смогу сделать, к примеру, сдвиг минус 5, к примеру - для A этот индекс будет == -5, что выйдет за границы, но по факту же для латинских "ABCDEFGHIJKLMNOPQRSTUVWXYZ" сдвиг минус 5 должен быть 21й буквой (V, кажется). Таким образом у меня решена проблема так называемой "ленты" Цезаря (она получается как бы склеенной "начало-конец")

2018-05-09 08:47 UTC, ilpoli approved these changes

2018-05-11 08:07 UTC, merged