Working with files commit
Archangel37/CaesarCipher pull request #2
Opened 2018-05-21 18:21 UTC by Archangel37

2018-05-22 05:12 UTC, ilpoli requested changes

2018-05-22 05:12 UTC, ilpoli commented on СaesarCipher/EncoderDecoder.cs
> +        public static string Code(string input, int shift)
Со строками это еще пройдет, а вот с файлом то не очень. мне бы не хотелось чтоб после шифрования и дешифрования текст менялся (в большой регистр), плюс знаки препинания, цифры и т.д. не могут быть обработаны.

2018-05-22 05:12 UTC, ilpoli commented on СaesarCipher/EncoderDecoder.cs
> +        public static string Code(string input, int shift)
В общем, не серьезно это все сейчас. Надо дописать до более взрослой программы.

2018-05-22 05:28 UTC, Archangel37 commented on СaesarCipher/EncoderDecoder.cs
> +        public static string Code(string input, int shift)
эммм, на тему менялся - не понял - у меня регистр не меняется, сам тестил лично =) если будет HeLLo WoRld!  -> (shift 3) KhOOr ZrUog! - аналогично и с РУ алфавитом.. Наверное, смутило, что я правил под то, что ты говорил - алфавиты у меня изначально в одном регистре, а потом я к ним добавляю каждому другой регистр..  со знаками препинания и цифрами - да, тут не добавлял, пока не придумал, как их сдвигать..

2018-05-23 07:13 UTC, ilpoli requested changes

2018-05-23 07:13 UTC, ilpoli commented on СaesarCipher/ChiffreDeVigenere.cs
> +                    : (byte) Math.Abs((b - key[_keyIndex]) % byte.MaxValue);
у тебя отличие только в знаке минус, зачем целое условие делать то?
сделал бы
```
var sign = code?1:-1;
Math.Abs((b + code*key[_keyIndex]) % byte.MaxValue)
```

а вообще лучше два метода сделать, потому что code аргумент полностью меняет способ работы. и было бы у тебя метода Encode и Decode, при чем текущий метод можешь оставить, просто сделаешь его private.

2018-05-23 07:13 UTC, ilpoli commented on СaesarCipher/ChiffreDeVigenere.cs
> +                    : (byte) Math.Abs((b - key[_keyIndex]) % byte.MaxValue);
Не уверен что тут код правильный.
Например у нас 33 буквы, ключ 3. Шифруем: букву я, получаем 33+3=36 остаток от деления на 33 дает 3.
```(byte) ((b + key[_keyIndex]) % byte.MaxValue)```
Теперь возвращаем все обратно |(3-3)%33)| получаем 0, а должно быть 33, а если будет отрицательно число, то мы как бы циклически с конца должны начать а вместо этого получим цикл с сначала, например при -1, расшифровать должны в 32, а получим просто 1.

2018-05-23 08:38 UTC, Archangel37 commented on СaesarCipher/ChiffreDeVigenere.cs
> +                    : (byte) Math.Abs((b - key[_keyIndex]) % byte.MaxValue);
По второму комменту - ты немного перепутал в формуле - я беру остаток от деления на byte.MaxValue == 255, поэтому получается в твоём случае (33+3)%255 == 36.. и (36-3)%255 == 33 - тут всё правильно работает.. 
Ошибка в другом месте=)) я неправильно делаю для отрицательных значений - не надо модуль брать.. у меня получается, что, к примеру (10-20)%255 == 10, а должно быть 255+(10-20) == 245..

2018-06-06 11:07 UTC, ilpoli approved these changes

2018-06-06 13:10 UTC, merged